### ISSUE TITLE
did you try move mouse in minecraft use AHK?

### ISSUE THREAD

**Issue by 911061873** [monpjc/XAHK#12]
The following is translated by Google, if there is a problem with the sentence, sorry。
I want to use some scripts to move the mouse in ~my world~ minecraft 。
I have tried many methods and none of them worked.

winapi *wm_sendmessage  wm_postmessage*
Click work, but moving the mouse doesn't work

ahk
Click work，Move mouse always look down and rotate

Have you tried it?
谢谢！thank you！

**Comment by pazgold31** [comment]
Disclaimer: I am not officially related to the program in any way.
I have successfully moved the mouse using AutoHotKeys  in minecraft, you should just use the MouseMove method.
