### ISSUE TITLE
Program can target any window

### ISSUE THREAD

**Issue by Fran314** [monpjc/XAHK#13]
Even though there is a part of the code that checks for the class of the targeted window and checks if it's a Minecraft window or not (checks if it's a GLFW30), the program actually allows you to target any type of window. I think I've found why there's this bug, and it's all at line 12. Instead of being:
`targetwinclass := GLFW30`
it should be
`targetwinclass := "GLFW30"`

That's because with the := operator, AutoHotKey doesn't treat the righthandside as a literal string but as the name of a (non-existing) variable. With the "..." it will now treat it as a literal string.

This bug made it so that at line 78, when the InStr looked for targetwinclass inside of targetclass, it was actually looking for the empty string (I'm assuming it's the default value of a non-existing variable) inside whatever targetclass was, and because it was empty it could ALWAYS find it inside any other string.

It's not that important of a bug since it didn't allow the user to make any really dangerous stuff, but since the code for the check was already there, I thought it wouldn't hurt to fix it!

By the way, that's the same reason why the declared wintitle can't actually be used as the title of the window when showing the GUI. By initializing wintitle as
`wintitle := "Minecraft X-AHK V0.4"`
and calling it in Gui Show as
`Gui, Show,, %wintitle %`
it will actually show the desidered title

**Comment by monpjc** [comment]
Thank you for this and the details :) I will include a fix and check that this works in the next release.

**Comment by monpjc** [comment]
Fixed and in next release
