### ISSUE TITLE
Autoclicker too slow for some farms

### ISSUE THREAD

**Issue by Wrydfell** [monpjc/XAHK#16]
I use this autoclicker on mob grinder mode for an enderman farm and it works perfectly. However, using this on a raid farm is fatal, as clicks are too slow to reliably kill evokers before they summon vex. An option to choose click delay would be ideal, but the optimum click delay would be 650ms, as that is the fastest you can attack fully with the diamond sword attack speed. An option to disable auto eating would also help with a raid farm, as that causes issues with right clicking while being moved

**Comment by crazycga** [comment]
Agreed; I personally was about to see if I could fix this issue.  The auto-eating would be a nice feature to turn off because it really screws the user when near chests.

**Comment by monpjc** [comment]
Same issue as #15
