### ISSUE TITLE
Alt-tabbing after setting up auto-fish pauses game

### ISSUE THREAD

**Issue by Tikkle** [monpjc/XAHK#17]
In Xisuma's video, it showed that you could alt-tab and the game wouldn't pause. Whenever I run the auto clicker and alt-tab it takes me to the pause menu. I don't know why it does. Is there a setting I'm missing?

**Comment by Ragingfire105** [comment]
This is a game setting toggled through F3+P.  This toggles the pause on lose of focus setting.

https://minecraft.gamepedia.com/Controls

**Comment by Tikkle** [comment]
After playing Minecraft for over 7 years. I only have 2 words. Holy Sh*t. I didn't know that. Thank you for enlightening my life @Ragingfire105
