### ISSUE TITLE
[Feature Request] Cobblestone miner

### ISSUE THREAD

**Issue by AverageComet250** [monpjc/XAHK#18]
An option to farm cobblestone would be nice. I'm currently using the concrete method instead, but it's not the best. Maybe a slider to set the length of each click and an option for how long the gap between each click is?

**Comment by AverageComet250** [comment]
I'd try adding the function myself and adding a pull-request but I'm terrible with ahk scripts.

**Comment by monpjc** [comment]
Thank you for your idea, have added it to the list of features to add.

**Comment by monpjc** [comment]
See #10 for updates
