### ISSUE TITLE
Minimize to taskbar

### ISSUE THREAD

**Issue by Araraura** [monpjc/XAHK#19]
Hey, would it be possible for this program to get an update which will give it the option to minimize to taskbar?

**Comment by Ragingfire105** [comment]
The main gui already minimizes to the taskbar.  Do you mean system tray as mentioned in #22 ?

**Comment by monpjc** [comment]
There is a lot of clean up going on for v1.0 - see #23 for feedback

**Comment by histefanhere** [comment]
Hi,

This feature has just been merged into main. Closing this issue.
