### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by AverageComet250** [monpjc/XAHK#22]
I know that someone asked for a feature similar (#19) but I think what would be better is having the script's window disappear and having mc minimize to the taskbar. I do know that this may not be possible, but It would be a great feature.

**Comment by Ragingfire105** [comment]
Added pull request (#23) with this functionality added.

**Comment by monpjc** [comment]
See #23

**Comment by histefanhere** [comment]
This feature has now been merged! Closing this issue.
