### ISSUE TITLE
Alt Tab on Concrete

### ISSUE THREAD

**Issue by monpjc** [monpjc/XAHK#4]
Posted by "ArmouredMonkey" via Xisuma x-ahk discord channel [https://discord.gg/xisuma](url)

> I am not sure if it is me, but the concrete option doesn't seem to keep going when you alt+tab to change window. (Done F3+P to ensure the game doesn't pause). I have managed to get it working by having the x-ahk window open over minecraft then doing ctrl+alt+c to start it. I have probably been doing that with the fishing too so that is my bad

**Comment by Kyodraco** [comment]
Hi, seems that it's doing it on my side too. When the X-AHK clicker is enabled on "concrete mode", it starts mining but stops whenever I switch to another program.
So, I hope it will be corrected soon ;)

**Comment by monpjc** [comment]
Have updated code to allow Alt-Tab to work when switching away from Minecraft. Have noticed that there is a issue with time the mouse buttons are held down - will be automatically fixed when GUI update is completed.
