### ISSUE TITLE
Generator and concrete modes stop working after alt+tabbing

### ISSUE THREAD

**Issue by hxllv** [monpjc/XAHK#41]
Upon inspection, modifying the Generator function to:
```
Generator:
{
	BreakLoop := 0

	While (BreakLoop = 0)
	{
		If (BreakLoop = 1)
		{
			sleep 10
		}

		ControlClick, , ahk_id %id%, ,Left, , NAD
		sleep 100
	}

	ControlClick, , ahk_id %id%, ,Left, , NAU
	Sleep 100
	Return
}
```

a.k.a moving the `ControlClick, , ahk_id %id%, ,Left, , NAD` to inside the while block, makes it function properly.

**Comment by histefanhere** [comment]
Thanks for making this issue! The solution is dead simple and I've just tested it in-game; not sure how I missed this :/. Creating a commit now!
